title: Sathvi Siva
description: Data Scientist

url: http://sathvisiva.github.io

baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: sathvisiva
  twitter: sathvisiva
  email: sathvisiva@gmail.com

google_analytics: "UA-58263416-1"
